// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated from the database editor. Edit data via the editor UI, then regenerate.

import { IActor } from '@/core/models/types'

export const Actors: IActor[] = [
  { id: 1, categoryId: 1, parentId: null, name: "Solar system barycenter", description: "", color: "#ffffff" },
  { id: 2, categoryId: 1, parentId: 1, name: "Earth system barycenter", description: "", color: "#ffffff" },
  { id: 3, categoryId: 1, parentId: 1, name: "Pluto system barycenter", description: "", color: "#ffffff" },
  { id: 4, categoryId: 3, parentId: 1, name: "Sun", description: "", color: "#ffffff" },
  { id: 5, categoryId: 4, parentId: 1, name: "Mercury", description: "", color: "#ffffff" },
  { id: 6, categoryId: 4, parentId: 1, name: "Venus", description: "", color: "#ffffff" },
  { id: 7, categoryId: 4, parentId: 2, name: "Earth", description: "", color: "#ffffff" },
  { id: 8, categoryId: 4, parentId: 1, name: "Mars", description: "", color: "#ffffff" },
  { id: 9, categoryId: 4, parentId: 1, name: "Ceres", description: "", color: "#ffffff" },
  { id: 10, categoryId: 4, parentId: 1, name: "Jupiter", description: "", color: "#ffffff" },
  { id: 11, categoryId: 4, parentId: 1, name: "Saturn", description: "", color: "#ffffff" },
  { id: 12, categoryId: 4, parentId: 1, name: "Uranus", description: "", color: "#ffffff" },
  { id: 13, categoryId: 4, parentId: 1, name: "Neptune", description: "", color: "#ffffff" },
  { id: 14, categoryId: 4, parentId: 3, name: "Pluto", description: "", color: "#ffffff" },
  { id: 15, categoryId: 4, parentId: 1, name: "Haumea", description: "", color: "#ffffff" },
  { id: 16, categoryId: 4, parentId: 1, name: "Makemake", description: "", color: "#ffffff" },
  { id: 17, categoryId: 4, parentId: 1, name: "Eris", description: "", color: "#ffffff" },
  { id: 18, categoryId: 4, parentId: 1, name: "Sedna", description: "", color: "#ffffff" },
  { id: 19, categoryId: 4, parentId: 2, name: "Moon", description: "", color: "#ffffff" },
  { id: 20, categoryId: 4, parentId: 10, name: "Io", description: "", color: "#ffffff" },
  { id: 21, categoryId: 4, parentId: 10, name: "Europa", description: "", color: "#ffffff" },
  { id: 22, categoryId: 4, parentId: 10, name: "Ganymede", description: "", color: "#ffffff" },
  { id: 23, categoryId: 4, parentId: 10, name: "Callisto", description: "", color: "#ffffff" },
  { id: 24, categoryId: 4, parentId: 11, name: "Mimas", description: "", color: "#ffffff" },
  { id: 25, categoryId: 4, parentId: 11, name: "Enceladus", description: "", color: "#ffffff" },
  { id: 26, categoryId: 4, parentId: 11, name: "Tethys", description: "", color: "#ffffff" },
  { id: 27, categoryId: 4, parentId: 11, name: "Dione", description: "", color: "#ffffff" },
  { id: 28, categoryId: 4, parentId: 11, name: "Rhea", description: "", color: "#ffffff" },
  { id: 29, categoryId: 4, parentId: 11, name: "Titan", description: "", color: "#ffffff" },
  { id: 30, categoryId: 4, parentId: 11, name: "Iapetus", description: "", color: "#ffffff" },
  { id: 31, categoryId: 4, parentId: 12, name: "Miranda", description: "", color: "#ffffff" },
  { id: 32, categoryId: 4, parentId: 12, name: "Ariel", description: "", color: "#ffffff" },
  { id: 33, categoryId: 4, parentId: 12, name: "Umbriel", description: "", color: "#ffffff" },
  { id: 34, categoryId: 4, parentId: 12, name: "Titania", description: "", color: "#ffffff" },
  { id: 35, categoryId: 4, parentId: 12, name: "Oberon", description: "", color: "#ffffff" },
  { id: 36, categoryId: 4, parentId: 13, name: "Triton", description: "", color: "#ffffff" },
  { id: 37, categoryId: 4, parentId: 3, name: "Charon", description: "", color: "#ffffff" },
  { id: 38, categoryId: 4, parentId: 17, name: "Dysnomia", description: "", color: "#ffffff" },
  { id: 39, categoryId: 6, parentId: 11, name: "Saturn", description: "", color: "#ffffff" },
  { id: 40, categoryId: 6, parentId: 12, name: "Uranus", description: "", color: "#ffffff" },
  { id: 41, categoryId: 6, parentId: 13, name: "Neptune", description: "", color: "#ffffff" }
]
