// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated from the database editor. Edit data via the editor UI, then regenerate.

import { IActor } from '@/core/models/types'

export const Actors: IActor[] = [
  { id: 1, categoryId: 1, parentId: null, name: "Solar system barycenter", description: "", color: "#ffff00" },
  { id: 2, categoryId: 1, parentId: 1, name: "Earth system barycenter", description: "", color: "#6495ed" },
  { id: 3, categoryId: 1, parentId: 1, name: "Pluto system barycenter", description: "", color: "#c9cfd2" },
  { id: 4, categoryId: 3, parentId: 1, name: "Sun", description: "", color: "#ffff00" },
  { id: 5, categoryId: 4, parentId: 1, name: "Mercury", description: "", color: "#a8a6a6" },
  { id: 6, categoryId: 4, parentId: 1, name: "Venus", description: "", color: "#cd853f" },
  { id: 7, categoryId: 4, parentId: 2, name: "Earth", description: "", color: "#6495ed" },
  { id: 8, categoryId: 4, parentId: 1, name: "Mars", description: "", color: "#b22222" },
  { id: 9, categoryId: 4, parentId: 1, name: "Ceres", description: "", color: "#939191" },
  { id: 10, categoryId: 4, parentId: 1, name: "Jupiter", description: "", color: "#f17c7c" },
  { id: 11, categoryId: 4, parentId: 1, name: "Saturn", description: "", color: "#cc9e26" },
  { id: 12, categoryId: 4, parentId: 1, name: "Uranus", description: "", color: "#6fc5c2" },
  { id: 13, categoryId: 4, parentId: 1, name: "Neptune", description: "", color: "#0f7eb9" },
  { id: 14, categoryId: 4, parentId: 3, name: "Pluto", description: "", color: "#c9cfd2" },
  { id: 15, categoryId: 4, parentId: 1, name: "Haumea", description: "", color: "#c9cfd2" },
  { id: 16, categoryId: 4, parentId: 1, name: "Makemake", description: "", color: "#c9cfd2" },
  { id: 17, categoryId: 4, parentId: 1, name: "Eris", description: "", color: "#c9cfd2" },
  { id: 18, categoryId: 4, parentId: 1, name: "Sedna", description: "", color: "#c9cfd2" },
  { id: 19, categoryId: 4, parentId: 2, name: "Moon", description: "", color: "#c9cfd2" },
  { id: 20, categoryId: 4, parentId: 10, name: "Io", description: "", color: "#c9cfd2" },
  { id: 21, categoryId: 4, parentId: 10, name: "Europa", description: "", color: "#c9cfd2" },
  { id: 22, categoryId: 4, parentId: 10, name: "Ganymede", description: "", color: "#c9cfd2" },
  { id: 23, categoryId: 4, parentId: 10, name: "Callisto", description: "", color: "#c9cfd2" },
  { id: 24, categoryId: 4, parentId: 11, name: "Mimas", description: "", color: "#c9cfd2" },
  { id: 25, categoryId: 4, parentId: 11, name: "Enceladus", description: "", color: "#c9cfd2" },
  { id: 26, categoryId: 4, parentId: 11, name: "Tethys", description: "", color: "#c9cfd2" },
  { id: 27, categoryId: 4, parentId: 11, name: "Dione", description: "", color: "#c9cfd2" },
  { id: 28, categoryId: 4, parentId: 11, name: "Rhea", description: "", color: "#c9cfd2" },
  { id: 29, categoryId: 4, parentId: 11, name: "Titan", description: "", color: "#c9cfd2" },
  { id: 30, categoryId: 4, parentId: 11, name: "Iapetus", description: "", color: "#c9cfd2" },
  { id: 31, categoryId: 4, parentId: 12, name: "Miranda", description: "", color: "#c9cfd2" },
  { id: 32, categoryId: 4, parentId: 12, name: "Ariel", description: "", color: "#c9cfd2" },
  { id: 33, categoryId: 4, parentId: 12, name: "Umbriel", description: "", color: "#c9cfd2" },
  { id: 34, categoryId: 4, parentId: 12, name: "Titania", description: "", color: "#c9cfd2" },
  { id: 35, categoryId: 4, parentId: 12, name: "Oberon", description: "", color: "#c9cfd2" },
  { id: 36, categoryId: 4, parentId: 13, name: "Triton", description: "", color: "#c9cfd2" },
  { id: 37, categoryId: 4, parentId: 3, name: "Charon", description: "", color: "#c9cfd2" },
  { id: 38, categoryId: 4, parentId: 17, name: "Dysnomia", description: "", color: "#c9cfd2" },
  { id: 39, categoryId: 6, parentId: 11, name: "Saturn", description: "", color: "#ffffff" },
  { id: 40, categoryId: 6, parentId: 12, name: "Uranus", description: "", color: "#ffffff" },
  { id: 41, categoryId: 6, parentId: 13, name: "Neptune", description: "", color: "#ffffff" },
  { id: 42, categoryId: 1, parentId: null, name: "Sgr A* system barycenter", description: "", color: "#ffffff" },
  { id: 43, categoryId: 2, parentId: 42, name: "Sgr A*", description: "", color: "#ffffff" },
  { id: 44, categoryId: 4, parentId: 42, name: "Sgr A* I", description: "", color: "#2e78da" },
  { id: 45, categoryId: 6, parentId: 44, name: "Sgr A* I", description: "", color: "#ffffff" },
  { id: 46, categoryId: 5, parentId: 6, name: "Venus", description: "", color: "#ffffff" },
  { id: 47, categoryId: 5, parentId: 7, name: "Earth", description: "", color: "#ffffff" },
  { id: 48, categoryId: 5, parentId: 8, name: "Mars", description: "", color: "#ffffff" },
  { id: 49, categoryId: 5, parentId: 10, name: "Jupiter", description: "", color: "#ffffff" },
  { id: 50, categoryId: 5, parentId: 11, name: "Saturn", description: "", color: "#ffffff" },
  { id: 51, categoryId: 5, parentId: 12, name: "Uranus", description: "", color: "#ffffff" },
  { id: 52, categoryId: 5, parentId: 13, name: "Neptune", description: "", color: "#ffffff" },
  { id: 53, categoryId: 5, parentId: 29, name: "Titan", description: "", color: "#ffffff" },
  { id: 54, categoryId: 5, parentId: 44, name: "Sgr A* I", description: "", color: "#ffffff" },
  { id: 55, categoryId: 1, parentId: null, name: "TOI-519 system barycenter", description: "", color: "#ef3535" },
  { id: 56, categoryId: 3, parentId: 55, name: "TOI-519", description: "", color: "#ef3535" },
  { id: 57, categoryId: 4, parentId: 55, name: "TOI-519b", description: "", color: "#2e78da" },
  { id: 58, categoryId: 5, parentId: 57, name: "TOI-519b", description: "", color: "#ffffff" },
  { id: 59, categoryId: 1, parentId: null, name: "Tatoo system barycenter", description: "", color: "#ffffff" },
  { id: 60, categoryId: 3, parentId: 59, name: "Tatoo I", description: "", color: "#e5e55a" },
  { id: 61, categoryId: 3, parentId: 59, name: "Tatoo II", description: "", color: "#ffffff" },
  { id: 62, categoryId: 4, parentId: 59, name: "Tatooine", description: "", color: "#cd853f" },
  { id: 63, categoryId: 4, parentId: 59, name: "Ohann", description: "", color: "#d7bb5f" },
  { id: 64, categoryId: 4, parentId: 59, name: "Adriana", description: "", color: "#2f9ece" },
  { id: 65, categoryId: 4, parentId: 62, name: "Ghomrassen", description: "", color: "#888684" },
  { id: 66, categoryId: 4, parentId: 62, name: "Guermessa", description: "", color: "#83684c" },
  { id: 67, categoryId: 4, parentId: 62, name: "Chenini", description: "", color: "#888787" },
  { id: 68, categoryId: 4, parentId: 63, name: "Ohann I", description: "", color: "#b4b4b4" },
  { id: 69, categoryId: 4, parentId: 63, name: "Ohann II", description: "", color: "#b4b4b4" },
  { id: 70, categoryId: 4, parentId: 63, name: "Ohann III", description: "", color: "#b4b4b4" },
  { id: 71, categoryId: 4, parentId: 64, name: "Adriana I", description: "", color: "#b4b4b4" },
  { id: 72, categoryId: 4, parentId: 64, name: "Adriana II", description: "", color: "#b4b4b4" },
  { id: 73, categoryId: 4, parentId: 64, name: "Adriana III", description: "", color: "#b4b4b4" },
  { id: 74, categoryId: 4, parentId: 64, name: "Adriana IV", description: "", color: "#b4b4b4" },
  { id: 75, categoryId: 5, parentId: 62, name: "Tatooine", description: "", color: "#ffffff" },
  { id: 76, categoryId: 5, parentId: 63, name: "Ohann", description: "", color: "#ffffff" },
  { id: 77, categoryId: 5, parentId: 64, name: "Adriana", description: "", color: "#ffffff" },
  { id: 78, categoryId: 5, parentId: 73, name: "Adriana III", description: "", color: "#ffffff" },
  { id: 79, categoryId: 6, parentId: 64, name: "Adriana", description: "", color: "#ffffff" },
  { id: 80, categoryId: 1, parentId: null, name: "Yavin system barycenter", description: "", color: "#ffffff" },
  { id: 81, categoryId: 3, parentId: 80, name: "Yavin", description: "", color: "#de8623" },
  { id: 82, categoryId: 4, parentId: 80, name: "Yavin Prime", description: "", color: "#ea4123" },
  { id: 83, categoryId: 4, parentId: 82, name: "Yavin IV", description: "", color: "#178f28" },
  { id: 84, categoryId: 5, parentId: 82, name: "Yavin Prime", description: "", color: "#ffffff" },
  { id: 85, categoryId: 5, parentId: 83, name: "Yavin IV", description: "", color: "#ffffff" },
  { id: 86, categoryId: 1, parentId: null, name: "Horuset system barycenter", description: "", color: "#ffffff" },
  { id: 87, categoryId: 3, parentId: 86, name: "Horuset", description: "", color: "#e4d52f" },
  { id: 88, categoryId: 4, parentId: 86, name: "Korriban", description: "", color: "#f3852b" },
  { id: 89, categoryId: 5, parentId: 88, name: "Korriban", description: "", color: "#ffffff" },
  { id: 90, categoryId: 4, parentId: 86, name: "Darkness", description: "", color: "#1994b3" },
  { id: 91, categoryId: 5, parentId: 90, name: "Darkness", description: "", color: "#ffffff" },
  { id: 92, categoryId: 6, parentId: 90, name: "Darkness", description: "", color: "#ffffff" },
  { id: 93, categoryId: 4, parentId: 88, name: "Korriban I", description: "", color: "#969696" },
  { id: 94, categoryId: 4, parentId: 88, name: "Korriban II", description: "", color: "#969696" },
  { id: 95, categoryId: 4, parentId: 88, name: "Korriban III", description: "", color: "#969696" },
  { id: 96, categoryId: 4, parentId: 88, name: "Korriban IV", description: "", color: "#969696" },
  { id: 97, categoryId: 4, parentId: 88, name: "Korriban V", description: "", color: "#969696" },
  { id: 98, categoryId: 4, parentId: 88, name: "Korriban VI", description: "", color: "#969696" },
  { id: 99, categoryId: 4, parentId: 88, name: "Korriban VII", description: "", color: "#969696" }
]
