// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated from the database editor. Edit data via the editor UI, then regenerate.

import { RepeatWrapping } from 'three'
import { IResource } from '@/core/models/types'

export const Resources: IResource[] = [
  { id: 1, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/px.jpg" },
  { id: 2, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nx.jpg" },
  { id: 3, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/py.jpg" },
  { id: 4, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/ny.jpg" },
  { id: 5, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/pz.jpg" },
  { id: 6, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nz.jpg" },
  { id: 7, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/px.png" },
  { id: 8, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nx.png" },
  { id: 9, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/py.png" },
  { id: 10, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/ny.png" },
  { id: 11, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/pz.png" },
  { id: 12, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nz.png" },
  { id: 13, resourceType: "diffuse", lifecycle: "resident", path: "default.png", colorSpace: "srgb-linear" },
  { id: 14, resourceType: "diffuse", lifecycle: "resident", path: "night.jpg" },
  { id: 15, resourceType: "diffuse", lifecycle: "resident", path: "star.png", colorSpace: "" },
  { id: 16, resourceType: "diffuse", lifecycle: "resident", path: "round.png", colorSpace: "srgb" },
  { id: 17, resourceType: "diffuse", lifecycle: "resident", path: "asteroid.jpg" },
  { id: 18, resourceType: "diffuse", lifecycle: "resident", path: "asteroid_bump.jpg" },
  { id: 19, resourceType: "diffuse", lifecycle: "resident", path: "sun.png", colorSpace: "srgb" },
  { id: 20, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mercury/mercury.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 21, resourceType: "bump", lifecycle: "streamable", path: "planets/mercury/mercury_bump.jpg" },
  { id: 22, resourceType: "diffuse", lifecycle: "streamable", path: "planets/venus/venus.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 24, resourceType: "diffuse", lifecycle: "streamable", path: "planets/earth/earth.jpg", colorSpace: "srgb" },
  { id: 25, resourceType: "bump", lifecycle: "streamable", path: "planets/earth/earth_bump.jpg" },
  { id: 26, resourceType: "cloud", lifecycle: "streamable", path: "planets/earth/earth_clouds.jpg" },
  { id: 27, resourceType: "night", lifecycle: "streamable", path: "planets/earth/earth_night.jpg", colorSpace: "srgb" },
  { id: 28, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mars/mars.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 29, resourceType: "bump", lifecycle: "streamable", path: "planets/mars/mars_bump.jpg" },
  { id: 30, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ceres/ceres.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 31, resourceType: "bump", lifecycle: "streamable", path: "planets/ceres/ceres_bump.jpg" },
  { id: 32, resourceType: "diffuse", lifecycle: "streamable", path: "planets/jupiter/jupiter.jpg", colorSpace: "srgb" },
  { id: 33, resourceType: "diffuse", lifecycle: "streamable", path: "planets/saturn/saturn.jpg", colorSpace: "srgb" },
  { id: 34, resourceType: "bump", lifecycle: "streamable", path: "planets/saturn/saturn_bump.jpg" },
  { id: 35, resourceType: "diffuse", lifecycle: "streamable", path: "planets/uranus/uranus.png", colorSpace: "srgb" },
  { id: 36, resourceType: "diffuse", lifecycle: "streamable", path: "planets/neptune/neptune.jpg", colorSpace: "srgb" },
  { id: 37, resourceType: "cloud", lifecycle: "streamable", path: "planets/neptune/neptune_clouds.jpg" },
  { id: 38, resourceType: "diffuse", lifecycle: "streamable", path: "planets/pluto/pluto.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 39, resourceType: "bump", lifecycle: "streamable", path: "planets/pluto/pluto_bump.jpg" },
  { id: 40, resourceType: "diffuse", lifecycle: "streamable", path: "planets/haumea/haumea.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 41, resourceType: "diffuse", lifecycle: "streamable", path: "planets/makemake/makemake.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 42, resourceType: "bump", lifecycle: "streamable", path: "planets/makemake/makemake_bump.jpg" },
  { id: 43, resourceType: "diffuse", lifecycle: "streamable", path: "planets/eris/eris.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 44, resourceType: "bump", lifecycle: "streamable", path: "planets/eris/eris_bump.jpg" },
  { id: 45, resourceType: "diffuse", lifecycle: "streamable", path: "planets/sedna/sedna.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 46, resourceType: "bump", lifecycle: "streamable", path: "planets/sedna/sedna_bump.jpg" },
  { id: 47, resourceType: "diffuse", lifecycle: "streamable", path: "planets/moon/moon.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 48, resourceType: "slope", lifecycle: "streamable", path: "planets/moon/moon_slope.webp", wrapS: RepeatWrapping },
  { id: 49, resourceType: "diffuse", lifecycle: "streamable", path: "planets/io/io.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 50, resourceType: "bump", lifecycle: "streamable", path: "planets/io/io_bump.jpg" },
  { id: 51, resourceType: "diffuse", lifecycle: "streamable", path: "planets/europa/europa.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 52, resourceType: "bump", lifecycle: "streamable", path: "planets/europa/europa_bump.jpg" },
  { id: 53, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ganymede/ganymede.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 54, resourceType: "bump", lifecycle: "streamable", path: "planets/ganymede/ganymede_bump.jpg" },
  { id: 55, resourceType: "diffuse", lifecycle: "streamable", path: "planets/callisto/callisto.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 56, resourceType: "bump", lifecycle: "streamable", path: "planets/callisto/callisto_bump.jpg" },
  { id: 57, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mimas/mimas.jpg", colorSpace: "srgb" },
  { id: 58, resourceType: "bump", lifecycle: "streamable", path: "planets/mimas/mimas_bump.jpg" },
  { id: 59, resourceType: "diffuse", lifecycle: "streamable", path: "planets/enceladus/enceladus.jpg", colorSpace: "srgb" },
  { id: 60, resourceType: "bump", lifecycle: "streamable", path: "planets/enceladus/enceladus_bump.jpg" },
  { id: 61, resourceType: "diffuse", lifecycle: "streamable", path: "planets/tethys/tethys.jpg", colorSpace: "srgb" },
  { id: 62, resourceType: "bump", lifecycle: "streamable", path: "planets/tethys/tethys_bump.jpg" },
  { id: 63, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dione/dione.jpg", colorSpace: "srgb" },
  { id: 64, resourceType: "bump", lifecycle: "streamable", path: "planets/dione/dione_bump.jpg" },
  { id: 65, resourceType: "diffuse", lifecycle: "streamable", path: "planets/rhea/rhea.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 66, resourceType: "bump", lifecycle: "streamable", path: "planets/rhea/rhea_bump.jpg" },
  { id: 67, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titan/titan.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 68, resourceType: "bump", lifecycle: "streamable", path: "planets/titan/titan_bump.jpg" },
  { id: 70, resourceType: "diffuse", lifecycle: "streamable", path: "planets/iapetus/iapetus.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 71, resourceType: "bump", lifecycle: "streamable", path: "planets/iapetus/iapetus_bump.jpg" },
  { id: 72, resourceType: "diffuse", lifecycle: "streamable", path: "planets/miranda/miranda.jpg", colorSpace: "srgb" },
  { id: 73, resourceType: "bump", lifecycle: "streamable", path: "planets/miranda/miranda_bump.jpg" },
  { id: 74, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ariel/ariel.jpg", colorSpace: "srgb" },
  { id: 75, resourceType: "bump", lifecycle: "streamable", path: "planets/ariel/ariel_bump.jpg" },
  { id: 76, resourceType: "diffuse", lifecycle: "streamable", path: "planets/umbriel/umbriel.jpg", colorSpace: "srgb" },
  { id: 77, resourceType: "bump", lifecycle: "streamable", path: "planets/umbriel/umbriel_bump.jpg" },
  { id: 78, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titania/titania.jpg", colorSpace: "srgb" },
  { id: 79, resourceType: "bump", lifecycle: "streamable", path: "planets/titania/titania_bump.jpg" },
  { id: 80, resourceType: "diffuse", lifecycle: "streamable", path: "planets/oberon/oberon.jpg", colorSpace: "srgb" },
  { id: 81, resourceType: "bump", lifecycle: "streamable", path: "planets/oberon/oberon_bump.jpg" },
  { id: 82, resourceType: "diffuse", lifecycle: "streamable", path: "planets/triton/triton.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 83, resourceType: "bump", lifecycle: "streamable", path: "planets/triton/triton_bump.jpg" },
  { id: 84, resourceType: "diffuse", lifecycle: "streamable", path: "planets/charon/charon.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 85, resourceType: "bump", lifecycle: "streamable", path: "planets/charon/charon_bump.jpg" },
  { id: 86, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dysnomia/dysnomia.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 87, resourceType: "bump", lifecycle: "streamable", path: "planets/dysnomia/dysnomia_bump.jpg" },
  { id: 88, resourceType: "diffuse", lifecycle: "resident", path: "planets/saturn/saturn_rings.png", colorSpace: "srgb" },
  { id: 89, resourceType: "diffuse", lifecycle: "resident", path: "planets/uranus/uranus_rings.png", colorSpace: "srgb" },
  { id: 90, resourceType: "diffuse", lifecycle: "resident", path: "planets/neptune/neptune_rings.png", colorSpace: "srgb" },
  { id: 91, resourceType: "specular", lifecycle: "streamable", path: "planets/earth/earth_specular.jpg", colorSpace: "srgb" },
  { id: 92, resourceType: "diffuse", lifecycle: "streamable", path: "planets/exoplanets/toi_519b/toi_519b.jpg", colorSpace: "srgb" },
  { id: 93, resourceType: "night", lifecycle: "streamable", path: "planets/exoplanets/toi_519b/toi_519b_night.png" },
  { id: 94, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/tatooine/tatooine.png", colorSpace: "srgb" },
  { id: 95, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/ohann/ohann.png", colorSpace: "srgb" },
  { id: 96, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/adriana/adriana.png", colorSpace: "srgb" },
  { id: 97, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/ghomrassen/ghomrassen.png", colorSpace: "srgb" },
  { id: 98, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/guermessa/guermessa.png", colorSpace: "srgb" },
  { id: 99, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/chenini/chenini.png", colorSpace: "srgb" },
  { id: 100, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_5.png", colorSpace: "srgb" },
  { id: 101, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_6.png", colorSpace: "srgb" },
  { id: 102, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_7.png", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 103, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_1.png", colorSpace: "srgb" },
  { id: 104, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_3.png", colorSpace: "srgb" },
  { id: 105, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/adriana3/adriana3.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 106, resourceType: "bump", lifecycle: "streamable", path: "planets/StarWars/adriana3/adriana3_bump.jpg" },
  { id: 107, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_5.png", colorSpace: "srgb" },
  { id: 108, resourceType: "diffuse", lifecycle: "resident", path: "planets/StarWars/adriana/adriana_rings.png" },
  { id: 109, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/yavin/prime/yavin_prime.png", colorSpace: "srgb" },
  { id: 110, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/yavin/iv/iv.png", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 111, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban.png", colorSpace: "srgb" },
  { id: 112, resourceType: "bump", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban_bump.png" },
  { id: 113, resourceType: "cloud", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban_clouds.png", colorSpace: "srgb" },
  { id: 114, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/darkness/darkness.png", colorSpace: "srgb" },
  { id: 115, resourceType: "night", lifecycle: "streamable", path: "planets/StarWars/darkness/darkness_night.png" },
  { id: 116, resourceType: "diffuse", lifecycle: "resident", path: "planets/StarWars/darkness/darkness_rings.png", colorSpace: "" },
  { id: 117, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/korriban/i/i.jpg", colorSpace: "srgb", wrapS: RepeatWrapping },
  { id: 118, resourceType: "bump", lifecycle: "streamable", path: "planets/StarWars/korriban/i/i_bump.jpg" },
  { id: 119, resourceType: "diffuse", lifecycle: "resident", path: "asteroids/rock_boulder_dry_diff_2k.jpg", colorSpace: "srgb" },
  { id: 120, resourceType: "bump", lifecycle: "resident", path: "asteroids/rock_boulder_dry_nor_gl_2k.jpg" },
  { id: 121, resourceType: "bump", lifecycle: "resident", path: "asteroids/rock_boulder_dry_arm_2k.jpg" },
  { id: 122, resourceType: "diffuse", lifecycle: "resident", path: "asteroids/rocks_ground_04_diff_2k.jpg", colorSpace: "srgb" },
  { id: 123, resourceType: "bump", lifecycle: "resident", path: "asteroids/rocks_ground_04_nor_gl_2k.jpg" },
  { id: 124, resourceType: "bump", lifecycle: "resident", path: "asteroids/rocks_ground_04_arm_2k.jpg" },
  { id: 125, resourceType: "height", lifecycle: "resident", path: "planets/moon/moon_height.raw" },
  { id: 126, resourceType: "detailDiffuse", lifecycle: "streamable", path: "terrain/rocky_trail_diff.webp", wrapS: RepeatWrapping, wrapT: RepeatWrapping, colorSpace: "srgb" },
  { id: 127, resourceType: "detailNormal", lifecycle: "streamable", path: "terrain/rocky_trail_nor.webp", wrapS: RepeatWrapping, wrapT: RepeatWrapping },
  { id: 128, resourceType: "detailArm", lifecycle: "streamable", path: "terrain/rocky_trail_arm.webp", wrapS: RepeatWrapping, wrapT: RepeatWrapping },
  { id: 129, resourceType: "detailNormal2", lifecycle: "streamable", path: "terrain/moon_01_nor.webp", wrapS: RepeatWrapping, wrapT: RepeatWrapping },
  { id: 130, resourceType: "height", lifecycle: "resident", path: "planets/callisto/callisto_height.raw" },
  { id: 131, resourceType: "slope", lifecycle: "streamable", path: "planets/callisto/callisto_slope.webp", wrapS: RepeatWrapping },
  { id: 132, resourceType: "height", lifecycle: "resident", path: "planets/europa/europa_height.raw" },
  { id: 133, resourceType: "slope", lifecycle: "streamable", path: "planets/europa/europa_slope.webp", wrapS: RepeatWrapping },
  // Батч 18 спутников (терраформная арка synth-heightmap, scripts/batch-synth-heightmaps.ts):
  // 18 генераций height+slope, пути — <каталог диффуза/бампа тела>/<имя>_height.raw и _slope.webp;
  // Корribан I-VII — ПЕР-ТЕЛО карты (общий только вход-текстура, но семь
  // независимых генераций: общая карта в метрах под радиус I (1740 км)
  // давала VII (175 км) 577% ЕГО бюджета высоты — фикс-раунд 1, находка 2).
  { id: 134, resourceType: "height", lifecycle: "resident", path: "planets/io/io_height.raw" },
  { id: 135, resourceType: "slope", lifecycle: "streamable", path: "planets/io/io_slope.webp", wrapS: RepeatWrapping },
  { id: 136, resourceType: "height", lifecycle: "resident", path: "planets/ganymede/ganymede_height.raw" },
  { id: 137, resourceType: "slope", lifecycle: "streamable", path: "planets/ganymede/ganymede_slope.webp", wrapS: RepeatWrapping },
  { id: 138, resourceType: "height", lifecycle: "resident", path: "planets/rhea/rhea_height.raw" },
  { id: 139, resourceType: "slope", lifecycle: "streamable", path: "planets/rhea/rhea_slope.webp", wrapS: RepeatWrapping },
  { id: 140, resourceType: "height", lifecycle: "resident", path: "planets/titan/titan_height.raw" },
  { id: 141, resourceType: "slope", lifecycle: "streamable", path: "planets/titan/titan_slope.webp", wrapS: RepeatWrapping },
  { id: 142, resourceType: "height", lifecycle: "resident", path: "planets/iapetus/iapetus_height.raw" },
  { id: 143, resourceType: "slope", lifecycle: "streamable", path: "planets/iapetus/iapetus_slope.webp", wrapS: RepeatWrapping },
  { id: 144, resourceType: "height", lifecycle: "resident", path: "planets/triton/triton_height.raw" },
  { id: 145, resourceType: "slope", lifecycle: "streamable", path: "planets/triton/triton_slope.webp", wrapS: RepeatWrapping },
  { id: 146, resourceType: "height", lifecycle: "resident", path: "planets/charon/charon_height.raw" },
  { id: 147, resourceType: "slope", lifecycle: "streamable", path: "planets/charon/charon_slope.webp", wrapS: RepeatWrapping },
  { id: 148, resourceType: "height", lifecycle: "resident", path: "planets/dysnomia/dysnomia_height.raw" },
  { id: 149, resourceType: "slope", lifecycle: "streamable", path: "planets/dysnomia/dysnomia_slope.webp", wrapS: RepeatWrapping },
  { id: 150, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/adriana3/adriana3_height.raw" },
  { id: 151, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/adriana3/adriana3_slope.webp", wrapS: RepeatWrapping },
  { id: 152, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/yavin/iv/yavin4_height.raw" },
  { id: 153, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/yavin/iv/yavin4_slope.webp", wrapS: RepeatWrapping },
  { id: 154, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/ohann3_height.raw" },
  { id: 155, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/ohann3_slope.webp", wrapS: RepeatWrapping },
  { id: 156, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban1_height.raw" },
  { id: 157, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban1_slope.webp", wrapS: RepeatWrapping },
  { id: 158, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban2_height.raw" },
  { id: 159, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban2_slope.webp", wrapS: RepeatWrapping },
  { id: 160, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban3_height.raw" },
  { id: 161, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban3_slope.webp", wrapS: RepeatWrapping },
  { id: 162, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban4_height.raw" },
  { id: 163, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban4_slope.webp", wrapS: RepeatWrapping },
  { id: 164, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban5_height.raw" },
  { id: 165, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban5_slope.webp", wrapS: RepeatWrapping },
  { id: 166, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban6_height.raw" },
  { id: 167, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban6_slope.webp", wrapS: RepeatWrapping },
  { id: 168, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban7_height.raw" },
  { id: 169, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban7_slope.webp", wrapS: RepeatWrapping },
  // Девять твёрдых тел (Task 2 терраформной арки planets): планеты (Меркурий, Венера,
  // Марс, Церера) и карликовые (Плутон, Хаумеа, Макемаке, Эрида, Седна) — height+slope
  // каждого своей генерации (Марс — реальный DEM, остальные восемь — synth-heightmap).
  { id: 170, resourceType: "height", lifecycle: "resident", path: "planets/mercury/mercury_height.raw" },
  { id: 171, resourceType: "slope", lifecycle: "streamable", path: "planets/mercury/mercury_slope.webp", wrapS: RepeatWrapping },
  { id: 172, resourceType: "height", lifecycle: "resident", path: "planets/venus/venus_height.raw" },
  { id: 173, resourceType: "slope", lifecycle: "streamable", path: "planets/venus/venus_slope.webp", wrapS: RepeatWrapping },
  { id: 174, resourceType: "height", lifecycle: "resident", path: "planets/mars/mars_height.raw" },
  { id: 175, resourceType: "slope", lifecycle: "streamable", path: "planets/mars/mars_slope.webp", wrapS: RepeatWrapping },
  { id: 176, resourceType: "height", lifecycle: "resident", path: "planets/ceres/ceres_height.raw" },
  { id: 177, resourceType: "slope", lifecycle: "streamable", path: "planets/ceres/ceres_slope.webp", wrapS: RepeatWrapping },
  { id: 178, resourceType: "height", lifecycle: "resident", path: "planets/pluto/pluto_height.raw" },
  { id: 179, resourceType: "slope", lifecycle: "streamable", path: "planets/pluto/pluto_slope.webp", wrapS: RepeatWrapping },
  { id: 180, resourceType: "height", lifecycle: "resident", path: "planets/haumea/haumea_height.raw" },
  { id: 181, resourceType: "slope", lifecycle: "streamable", path: "planets/haumea/haumea_slope.webp", wrapS: RepeatWrapping },
  { id: 182, resourceType: "height", lifecycle: "resident", path: "planets/makemake/makemake_height.raw" },
  { id: 183, resourceType: "slope", lifecycle: "streamable", path: "planets/makemake/makemake_slope.webp", wrapS: RepeatWrapping },
  { id: 184, resourceType: "height", lifecycle: "resident", path: "planets/eris/eris_height.raw" },
  { id: 185, resourceType: "slope", lifecycle: "streamable", path: "planets/eris/eris_slope.webp", wrapS: RepeatWrapping },
  { id: 186, resourceType: "height", lifecycle: "resident", path: "planets/sedna/sedna_height.raw" },
  { id: 187, resourceType: "slope", lifecycle: "streamable", path: "planets/sedna/sedna_slope.webp", wrapS: RepeatWrapping }
]
