// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated from the database editor. Edit data via the editor UI, then regenerate.

import { IResource } from '@/core/models/types'

export const Resources: IResource[] = [
  { id: 1, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/px.jpg" },
  { id: 2, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nx.jpg" },
  { id: 3, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/py.jpg" },
  { id: 4, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/ny.jpg" },
  { id: 5, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/pz.jpg" },
  { id: 6, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nz.jpg" },
  { id: 7, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/px.png" },
  { id: 8, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nx.png" },
  { id: 9, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/py.png" },
  { id: 10, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/ny.png" },
  { id: 11, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/pz.png" },
  { id: 12, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nz.png" },
  { id: 13, resourceType: "diffuse", lifecycle: "resident", path: "default.png", colorSpace: "srgb-linear" },
  { id: 14, resourceType: "diffuse", lifecycle: "resident", path: "night.jpg" },
  { id: 15, resourceType: "diffuse", lifecycle: "resident", path: "star.png", colorSpace: "" },
  { id: 16, resourceType: "diffuse", lifecycle: "resident", path: "round.png", colorSpace: "srgb" },
  { id: 17, resourceType: "diffuse", lifecycle: "resident", path: "asteroid.jpg" },
  { id: 18, resourceType: "diffuse", lifecycle: "resident", path: "asteroid_bump.jpg" },
  { id: 19, resourceType: "diffuse", lifecycle: "resident", path: "sun.png", colorSpace: "srgb" },
  { id: 20, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mercury/mercury.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 22, resourceType: "diffuse", lifecycle: "streamable", path: "planets/venus/venus.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 24, resourceType: "diffuse", lifecycle: "streamable", path: "planets/earth/earth.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 26, resourceType: "cloud", lifecycle: "streamable", path: "planets/earth/earth_clouds.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 27, resourceType: "night", lifecycle: "streamable", path: "planets/earth/earth_night.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 28, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mars/mars.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 30, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ceres/ceres.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 32, resourceType: "diffuse", lifecycle: "streamable", path: "planets/jupiter/jupiter.jpg", colorSpace: "srgb" },
  { id: 33, resourceType: "diffuse", lifecycle: "streamable", path: "planets/saturn/saturn.jpg", colorSpace: "srgb" },
  { id: 35, resourceType: "diffuse", lifecycle: "streamable", path: "planets/uranus/uranus.png", colorSpace: "srgb" },
  { id: 36, resourceType: "diffuse", lifecycle: "streamable", path: "planets/neptune/neptune.jpg", colorSpace: "srgb" },
  { id: 37, resourceType: "cloud", lifecycle: "streamable", path: "planets/neptune/neptune_clouds.jpg", colorSpace: "srgb" },
  { id: 38, resourceType: "diffuse", lifecycle: "streamable", path: "planets/pluto/pluto.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 40, resourceType: "diffuse", lifecycle: "streamable", path: "planets/haumea/haumea.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 41, resourceType: "diffuse", lifecycle: "streamable", path: "planets/makemake/makemake.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 43, resourceType: "diffuse", lifecycle: "streamable", path: "planets/eris/eris.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 45, resourceType: "diffuse", lifecycle: "streamable", path: "planets/sedna/sedna.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 47, resourceType: "diffuse", lifecycle: "streamable", path: "planets/moon/moon.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 48, resourceType: "slope", lifecycle: "streamable", path: "planets/moon/moon_slope.webp", slopeRange: 1, wrapS: 1e3 },
  { id: 49, resourceType: "diffuse", lifecycle: "streamable", path: "planets/io/io.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 51, resourceType: "diffuse", lifecycle: "streamable", path: "planets/europa/europa.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 53, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ganymede/ganymede.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 55, resourceType: "diffuse", lifecycle: "streamable", path: "planets/callisto/callisto.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 57, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mimas/mimas.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 59, resourceType: "diffuse", lifecycle: "streamable", path: "planets/enceladus/enceladus.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 61, resourceType: "diffuse", lifecycle: "streamable", path: "planets/tethys/tethys.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 63, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dione/dione.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 65, resourceType: "diffuse", lifecycle: "streamable", path: "planets/rhea/rhea.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 67, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titan/titan.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 70, resourceType: "diffuse", lifecycle: "streamable", path: "planets/iapetus/iapetus.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 72, resourceType: "diffuse", lifecycle: "streamable", path: "planets/miranda/miranda.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 74, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ariel/ariel.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 76, resourceType: "diffuse", lifecycle: "streamable", path: "planets/umbriel/umbriel.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 78, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titania/titania.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 80, resourceType: "diffuse", lifecycle: "streamable", path: "planets/oberon/oberon.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 82, resourceType: "diffuse", lifecycle: "streamable", path: "planets/triton/triton.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 84, resourceType: "diffuse", lifecycle: "streamable", path: "planets/charon/charon.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 86, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dysnomia/dysnomia.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 88, resourceType: "diffuse", lifecycle: "resident", path: "planets/saturn/saturn_rings.png", colorSpace: "srgb" },
  { id: 89, resourceType: "diffuse", lifecycle: "resident", path: "planets/uranus/uranus_rings.png", colorSpace: "srgb" },
  { id: 90, resourceType: "diffuse", lifecycle: "resident", path: "planets/neptune/neptune_rings.png", colorSpace: "srgb" },
  { id: 91, resourceType: "specular", lifecycle: "streamable", path: "planets/earth/earth_specular.jpg", wrapS: 1e3 },
  { id: 92, resourceType: "diffuse", lifecycle: "streamable", path: "planets/exoplanets/toi_519b/toi_519b.jpg", colorSpace: "srgb" },
  { id: 93, resourceType: "night", lifecycle: "streamable", path: "planets/exoplanets/toi_519b/toi_519b_night.png", colorSpace: "srgb" },
  { id: 94, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/tatooine/tatooine.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 95, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/ohann/ohann.png", colorSpace: "srgb" },
  { id: 96, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/adriana/adriana.png", colorSpace: "srgb" },
  { id: 97, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/ghomrassen/ghomrassen.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 98, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/guermessa/guermessa.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 99, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/chenini/chenini.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 100, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_5.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 101, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_6.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 102, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_7.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 103, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_1.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 104, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_3.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 105, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/adriana3/adriana3.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 107, resourceType: "diffuse", lifecycle: "streamable", path: "planets/unnamed/unnamed_planet_5.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 108, resourceType: "diffuse", lifecycle: "resident", path: "planets/StarWars/adriana/adriana_rings.png" },
  { id: 109, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/yavin/prime/yavin_prime.png", colorSpace: "srgb" },
  { id: 110, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/yavin/iv/iv.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 111, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 113, resourceType: "cloud", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban_clouds.png", colorSpace: "srgb", wrapS: 1e3 },
  { id: 114, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/darkness/darkness.png", colorSpace: "srgb" },
  { id: 115, resourceType: "night", lifecycle: "streamable", path: "planets/StarWars/darkness/darkness_night.png", colorSpace: "srgb" },
  { id: 116, resourceType: "diffuse", lifecycle: "resident", path: "planets/StarWars/darkness/darkness_rings.png", colorSpace: "" },
  { id: 117, resourceType: "diffuse", lifecycle: "streamable", path: "planets/StarWars/korriban/i/i.jpg", colorSpace: "srgb", wrapS: 1e3 },
  { id: 119, resourceType: "diffuse", lifecycle: "resident", path: "asteroids/rock_boulder_dry_diff_2k.jpg", colorSpace: "srgb" },
  { id: 120, resourceType: "bump", lifecycle: "resident", path: "asteroids/rock_boulder_dry_nor_gl_2k.jpg" },
  { id: 121, resourceType: "bump", lifecycle: "resident", path: "asteroids/rock_boulder_dry_arm_2k.jpg" },
  { id: 122, resourceType: "diffuse", lifecycle: "resident", path: "asteroids/rocks_ground_04_diff_2k.jpg", colorSpace: "srgb" },
  { id: 123, resourceType: "bump", lifecycle: "resident", path: "asteroids/rocks_ground_04_nor_gl_2k.jpg" },
  { id: 124, resourceType: "bump", lifecycle: "resident", path: "asteroids/rocks_ground_04_arm_2k.jpg" },
  { id: 125, resourceType: "height", lifecycle: "resident", path: "planets/moon/moon_height.raw" },
  { id: 126, resourceType: "detailDiffuse", lifecycle: "streamable", path: "terrain/rocky_trail_diff.webp", wrapS: 1e3, wrapT: 1e3, colorSpace: "srgb" },
  { id: 127, resourceType: "detailNormal", lifecycle: "streamable", path: "terrain/rocky_trail_nor.webp", wrapS: 1e3, wrapT: 1e3 },
  { id: 128, resourceType: "detailArm", lifecycle: "streamable", path: "terrain/rocky_trail_arm.webp", wrapS: 1e3, wrapT: 1e3 },
  { id: 129, resourceType: "detailNormal2", lifecycle: "streamable", path: "terrain/moon_01_nor.webp", wrapS: 1e3, wrapT: 1e3 },
  { id: 130, resourceType: "height", lifecycle: "resident", path: "planets/callisto/callisto_height.raw" },
  { id: 131, resourceType: "slope", lifecycle: "streamable", path: "planets/callisto/callisto_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 132, resourceType: "height", lifecycle: "resident", path: "planets/europa/europa_height.raw" },
  { id: 133, resourceType: "slope", lifecycle: "streamable", path: "planets/europa/europa_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 134, resourceType: "height", lifecycle: "resident", path: "planets/io/io_height.raw" },
  { id: 135, resourceType: "slope", lifecycle: "streamable", path: "planets/io/io_slope.webp", slopeRange: 1, wrapS: 1e3 },
  { id: 136, resourceType: "height", lifecycle: "resident", path: "planets/ganymede/ganymede_height.raw" },
  { id: 137, resourceType: "slope", lifecycle: "streamable", path: "planets/ganymede/ganymede_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 138, resourceType: "height", lifecycle: "resident", path: "planets/rhea/rhea_height.raw" },
  { id: 139, resourceType: "slope", lifecycle: "streamable", path: "planets/rhea/rhea_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 140, resourceType: "height", lifecycle: "resident", path: "planets/titan/titan_height.raw" },
  { id: 141, resourceType: "slope", lifecycle: "streamable", path: "planets/titan/titan_slope.webp", slopeRange: 1, wrapS: 1e3 },
  { id: 142, resourceType: "height", lifecycle: "resident", path: "planets/iapetus/iapetus_height.raw" },
  { id: 143, resourceType: "slope", lifecycle: "streamable", path: "planets/iapetus/iapetus_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 144, resourceType: "height", lifecycle: "resident", path: "planets/triton/triton_height.raw" },
  { id: 145, resourceType: "slope", lifecycle: "streamable", path: "planets/triton/triton_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 146, resourceType: "height", lifecycle: "resident", path: "planets/charon/charon_height.raw" },
  { id: 147, resourceType: "slope", lifecycle: "streamable", path: "planets/charon/charon_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 148, resourceType: "height", lifecycle: "resident", path: "planets/dysnomia/dysnomia_height.raw" },
  { id: 149, resourceType: "slope", lifecycle: "streamable", path: "planets/dysnomia/dysnomia_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 150, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/adriana3/adriana3_height.raw" },
  { id: 151, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/adriana3/adriana3_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 152, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/yavin/iv/yavin4_height.raw" },
  { id: 153, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/yavin/iv/yavin4_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 154, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/ohann3_height.raw" },
  { id: 155, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/ohann3_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 156, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban1_height.raw" },
  { id: 157, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban1_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 158, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban2_height.raw" },
  { id: 159, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban2_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 160, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban3_height.raw" },
  { id: 161, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban3_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 162, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban4_height.raw" },
  { id: 163, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban4_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 164, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban5_height.raw" },
  { id: 165, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban5_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 166, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban6_height.raw" },
  { id: 167, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban6_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 168, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/i/korriban7_height.raw" },
  { id: 169, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/i/korriban7_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 170, resourceType: "height", lifecycle: "resident", path: "planets/mercury/mercury_height.raw" },
  { id: 171, resourceType: "slope", lifecycle: "streamable", path: "planets/mercury/mercury_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 172, resourceType: "height", lifecycle: "resident", path: "planets/venus/venus_height.raw" },
  { id: 173, resourceType: "slope", lifecycle: "streamable", path: "planets/venus/venus_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 174, resourceType: "height", lifecycle: "resident", path: "planets/mars/mars_height.raw" },
  { id: 175, resourceType: "slope", lifecycle: "streamable", path: "planets/mars/mars_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 176, resourceType: "height", lifecycle: "resident", path: "planets/ceres/ceres_height.raw" },
  { id: 177, resourceType: "slope", lifecycle: "streamable", path: "planets/ceres/ceres_slope.webp", slopeRange: 2, wrapS: 1e3 },
  { id: 178, resourceType: "height", lifecycle: "resident", path: "planets/pluto/pluto_height.raw" },
  { id: 179, resourceType: "slope", lifecycle: "streamable", path: "planets/pluto/pluto_slope.webp", slopeRange: 2, wrapS: 1e3 },
  { id: 180, resourceType: "height", lifecycle: "resident", path: "planets/haumea/haumea_height.raw" },
  { id: 181, resourceType: "slope", lifecycle: "streamable", path: "planets/haumea/haumea_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 182, resourceType: "height", lifecycle: "resident", path: "planets/makemake/makemake_height.raw" },
  { id: 183, resourceType: "slope", lifecycle: "streamable", path: "planets/makemake/makemake_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 184, resourceType: "height", lifecycle: "resident", path: "planets/eris/eris_height.raw" },
  { id: 185, resourceType: "slope", lifecycle: "streamable", path: "planets/eris/eris_slope.webp", slopeRange: 2, wrapS: 1e3 },
  { id: 186, resourceType: "height", lifecycle: "resident", path: "planets/sedna/sedna_height.raw" },
  { id: 187, resourceType: "slope", lifecycle: "streamable", path: "planets/sedna/sedna_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 188, resourceType: "height", lifecycle: "resident", path: "planets/mimas/mimas_height.raw" },
  { id: 189, resourceType: "slope", lifecycle: "streamable", path: "planets/mimas/mimas_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 190, resourceType: "height", lifecycle: "resident", path: "planets/enceladus/enceladus_height.raw" },
  { id: 191, resourceType: "slope", lifecycle: "streamable", path: "planets/enceladus/enceladus_slope.webp", slopeRange: 1, wrapS: 1e3 },
  { id: 192, resourceType: "height", lifecycle: "resident", path: "planets/tethys/tethys_height.raw" },
  { id: 193, resourceType: "slope", lifecycle: "streamable", path: "planets/tethys/tethys_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 194, resourceType: "height", lifecycle: "resident", path: "planets/dione/dione_height.raw" },
  { id: 195, resourceType: "slope", lifecycle: "streamable", path: "planets/dione/dione_slope.webp", slopeRange: 1, wrapS: 1e3 },
  { id: 196, resourceType: "height", lifecycle: "resident", path: "planets/miranda/miranda_height.raw" },
  { id: 197, resourceType: "slope", lifecycle: "streamable", path: "planets/miranda/miranda_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 198, resourceType: "height", lifecycle: "resident", path: "planets/ariel/ariel_height.raw" },
  { id: 199, resourceType: "slope", lifecycle: "streamable", path: "planets/ariel/ariel_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 200, resourceType: "height", lifecycle: "resident", path: "planets/umbriel/umbriel_height.raw" },
  { id: 201, resourceType: "slope", lifecycle: "streamable", path: "planets/umbriel/umbriel_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 202, resourceType: "height", lifecycle: "resident", path: "planets/titania/titania_height.raw" },
  { id: 203, resourceType: "slope", lifecycle: "streamable", path: "planets/titania/titania_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 204, resourceType: "height", lifecycle: "resident", path: "planets/oberon/oberon_height.raw" },
  { id: 205, resourceType: "slope", lifecycle: "streamable", path: "planets/oberon/oberon_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 206, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/tatooine/tatooine_height.raw" },
  { id: 207, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/tatooine/tatooine_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 208, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/ghomrassen/ghomrassen_height.raw" },
  { id: 209, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/ghomrassen/ghomrassen_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 210, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/guermessa/guermessa_height.raw" },
  { id: 211, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/guermessa/guermessa_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 212, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/chenini/chenini_height.raw" },
  { id: 213, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/chenini/chenini_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 214, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/ohann1_height.raw" },
  { id: 215, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/ohann1_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 216, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/ohann2_height.raw" },
  { id: 217, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/ohann2_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 218, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/adriana1_height.raw" },
  { id: 219, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/adriana1_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 220, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/adriana2_height.raw" },
  { id: 221, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/adriana2_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 222, resourceType: "height", lifecycle: "resident", path: "planets/unnamed/adriana4_height.raw" },
  { id: 223, resourceType: "slope", lifecycle: "streamable", path: "planets/unnamed/adriana4_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 224, resourceType: "height", lifecycle: "resident", path: "planets/StarWars/korriban/korriban_height.raw" },
  { id: 225, resourceType: "slope", lifecycle: "streamable", path: "planets/StarWars/korriban/korriban_slope.webp", slopeRange: 0.5, wrapS: 1e3 },
  { id: 226, resourceType: "height", lifecycle: "resident", path: "planets/earth/earth_height.raw" },
  { id: 227, resourceType: "slope", lifecycle: "streamable", path: "planets/earth/earth_slope.webp", slopeRange: 0.25, wrapS: 1e3 },
  { id: 228, resourceType: "waterNormal", lifecycle: "resident", path: "water/waternormals.jpg", wrapS: 1e3, wrapT: 1e3 }
]
