// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated from the database editor. Edit data via the editor UI, then regenerate.

import { IResource } from '@/core/models/types'

export const Resources: IResource[] = [
  { id: 1, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/px.jpg", lifetime: 6e4 },
  { id: 2, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nx.jpg", lifetime: 6e4 },
  { id: 3, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/py.jpg", lifetime: 6e4 },
  { id: 4, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/ny.jpg", lifetime: 6e4 },
  { id: 5, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/pz.jpg", lifetime: 6e4 },
  { id: 6, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/main/nz.jpg", lifetime: 6e4 },
  { id: 7, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/px.png", lifetime: 6e4 },
  { id: 8, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nx.png", lifetime: 6e4 },
  { id: 9, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/py.png", lifetime: 6e4 },
  { id: 10, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/ny.png", lifetime: 6e4 },
  { id: 11, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/pz.png", lifetime: 6e4 },
  { id: 12, resourceType: "cube", lifecycle: "resident", path: "cubemaps/scene/colored/nz.png", lifetime: 6e4 },
  { id: 13, resourceType: "diffuse", lifecycle: "resident", path: "default.png", lifetime: 6e4, colorSpace: "srgb-linear" },
  { id: 14, resourceType: "diffuse", lifecycle: "resident", path: "night.jpg", lifetime: 6e4 },
  { id: 15, resourceType: "diffuse", lifecycle: "resident", path: "star.png", lifetime: 6e4, colorSpace: "" },
  { id: 16, resourceType: "diffuse", lifecycle: "resident", path: "round.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 17, resourceType: "diffuse", lifecycle: "resident", path: "asteroid.jpg", lifetime: 6e4 },
  { id: 18, resourceType: "diffuse", lifecycle: "resident", path: "asteroid_bump.jpg", lifetime: 6e4 },
  { id: 19, resourceType: "diffuse", lifecycle: "resident", path: "sun.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 20, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mercury/mercury.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 21, resourceType: "bump", lifecycle: "streamable", path: "planets/mercury/mercury_bump.jpg", lifetime: 6e4 },
  { id: 22, resourceType: "diffuse", lifecycle: "streamable", path: "planets/venus/venus.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 23, resourceType: "cloud", lifecycle: "streamable", path: "planets/venus/venus_clouds.jpg", lifetime: 6e4 },
  { id: 24, resourceType: "diffuse", lifecycle: "streamable", path: "planets/earth/earth.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 25, resourceType: "bump", lifecycle: "streamable", path: "planets/earth/earth_bump.jpg", lifetime: 6e4 },
  { id: 26, resourceType: "cloud", lifecycle: "streamable", path: "planets/earth/earth_clouds.jpg", lifetime: 6e4 },
  { id: 27, resourceType: "night", lifecycle: "streamable", path: "planets/earth/earth_night.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 28, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mars/mars.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 29, resourceType: "bump", lifecycle: "streamable", path: "planets/mars/mars_bump.jpg", lifetime: 6e4 },
  { id: 30, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ceres/ceres.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 31, resourceType: "bump", lifecycle: "streamable", path: "planets/ceres/ceres_bump.jpg", lifetime: 6e4 },
  { id: 32, resourceType: "diffuse", lifecycle: "streamable", path: "planets/jupiter/jupiter.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 33, resourceType: "diffuse", lifecycle: "streamable", path: "planets/saturn/saturn.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 34, resourceType: "bump", lifecycle: "streamable", path: "planets/saturn/saturn_bump.jpg", lifetime: 6e4 },
  { id: 35, resourceType: "diffuse", lifecycle: "streamable", path: "planets/uranus/uranus.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 36, resourceType: "diffuse", lifecycle: "streamable", path: "planets/neptune/neptune.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 37, resourceType: "cloud", lifecycle: "streamable", path: "planets/neptune/neptune_clouds.jpg", lifetime: 6e4 },
  { id: 38, resourceType: "diffuse", lifecycle: "streamable", path: "planets/pluto/pluto.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 39, resourceType: "bump", lifecycle: "streamable", path: "planets/pluto/pluto_bump.jpg", lifetime: 6e4 },
  { id: 40, resourceType: "diffuse", lifecycle: "streamable", path: "planets/haumea/haumea.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 41, resourceType: "diffuse", lifecycle: "streamable", path: "planets/makemake/makemake.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 42, resourceType: "bump", lifecycle: "streamable", path: "planets/makemake/makemake_bump.jpg", lifetime: 6e4 },
  { id: 43, resourceType: "diffuse", lifecycle: "streamable", path: "planets/eris/eris.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 44, resourceType: "bump", lifecycle: "streamable", path: "planets/eris/eris_bump.jpg", lifetime: 6e4 },
  { id: 45, resourceType: "diffuse", lifecycle: "streamable", path: "planets/sedna/sedna.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 46, resourceType: "bump", lifecycle: "streamable", path: "planets/sedna/sedna_bump.jpg", lifetime: 6e4 },
  { id: 47, resourceType: "diffuse", lifecycle: "streamable", path: "planets/moon/moon.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 48, resourceType: "bump", lifecycle: "streamable", path: "planets/moon/moon_bump.jpg", lifetime: 6e4 },
  { id: 49, resourceType: "diffuse", lifecycle: "streamable", path: "planets/io/io.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 50, resourceType: "bump", lifecycle: "streamable", path: "planets/io/io_bump.jpg", lifetime: 6e4 },
  { id: 51, resourceType: "diffuse", lifecycle: "streamable", path: "planets/europa/europa.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 52, resourceType: "bump", lifecycle: "streamable", path: "planets/europa/europa_bump.jpg", lifetime: 6e4 },
  { id: 53, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ganymede/ganymede.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 54, resourceType: "bump", lifecycle: "streamable", path: "planets/ganymede/ganymede_bump.jpg", lifetime: 6e4 },
  { id: 55, resourceType: "diffuse", lifecycle: "streamable", path: "planets/callisto/callisto.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 56, resourceType: "bump", lifecycle: "streamable", path: "planets/callisto/callisto_bump.jpg", lifetime: 6e4 },
  { id: 57, resourceType: "diffuse", lifecycle: "streamable", path: "planets/mimas/mimas.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 58, resourceType: "bump", lifecycle: "streamable", path: "planets/mimas/mimas_bump.jpg", lifetime: 6e4 },
  { id: 59, resourceType: "diffuse", lifecycle: "streamable", path: "planets/enceladus/enceladus.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 60, resourceType: "bump", lifecycle: "streamable", path: "planets/enceladus/enceladus_bump.jpg", lifetime: 6e4 },
  { id: 61, resourceType: "diffuse", lifecycle: "streamable", path: "planets/tethys/tethys.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 62, resourceType: "bump", lifecycle: "streamable", path: "planets/tethys/tethys_bump.jpg", lifetime: 6e4 },
  { id: 63, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dione/dione.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 64, resourceType: "bump", lifecycle: "streamable", path: "planets/dione/dione_bump.jpg", lifetime: 6e4 },
  { id: 65, resourceType: "diffuse", lifecycle: "streamable", path: "planets/rhea/rhea.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 66, resourceType: "diffuse", lifecycle: "streamable", path: "planets/rhea/rhea_bump.jpg", lifetime: 6e4 },
  { id: 67, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titan/titan.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 68, resourceType: "bump", lifecycle: "streamable", path: "planets/titan/titan_bump.jpg", lifetime: 6e4 },
  { id: 69, resourceType: "cloud", lifecycle: "streamable", path: "planets/titan/titan_clouds.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 70, resourceType: "diffuse", lifecycle: "streamable", path: "planets/iapetus/iapetus.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 71, resourceType: "bump", lifecycle: "streamable", path: "planets/iapetus/iapetus_bump.jpg", lifetime: 6e4 },
  { id: 72, resourceType: "diffuse", lifecycle: "streamable", path: "planets/miranda/miranda.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 73, resourceType: "bump", lifecycle: "streamable", path: "planets/miranda/miranda_bump.jpg", lifetime: 6e4 },
  { id: 74, resourceType: "diffuse", lifecycle: "streamable", path: "planets/ariel/ariel.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 75, resourceType: "bump", lifecycle: "streamable", path: "planets/ariel/ariel_bump.jpg", lifetime: 6e4 },
  { id: 76, resourceType: "diffuse", lifecycle: "streamable", path: "planets/umbriel/umbriel.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 77, resourceType: "bump", lifecycle: "streamable", path: "planets/umbriel/umbriel_bump.jpg", lifetime: 6e4 },
  { id: 78, resourceType: "diffuse", lifecycle: "streamable", path: "planets/titania/titania.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 79, resourceType: "bump", lifecycle: "streamable", path: "planets/titania/titania_bump.jpg", lifetime: 6e4 },
  { id: 80, resourceType: "diffuse", lifecycle: "streamable", path: "planets/oberon/oberon.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 81, resourceType: "bump", lifecycle: "streamable", path: "planets/oberon/oberon_bump.jpg", lifetime: 6e4 },
  { id: 82, resourceType: "diffuse", lifecycle: "streamable", path: "planets/triton/triton.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 83, resourceType: "bump", lifecycle: "streamable", path: "planets/triton/triton_bump.jpg", lifetime: 6e4 },
  { id: 84, resourceType: "diffuse", lifecycle: "streamable", path: "planets/charon/charon.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 85, resourceType: "bump", lifecycle: "streamable", path: "planets/charon/charon_bump.jpg", lifetime: 6e4 },
  { id: 86, resourceType: "diffuse", lifecycle: "streamable", path: "planets/dysnomia/dysnomia.jpg", lifetime: 6e4, colorSpace: "srgb" },
  { id: 87, resourceType: "bump", lifecycle: "streamable", path: "planets/dysnomia/dysnomia_bump.jpg", lifetime: 6e4 },
  { id: 88, resourceType: "diffuse", lifecycle: "resident", path: "planets/saturn/saturn_rings.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 89, resourceType: "diffuse", lifecycle: "resident", path: "planets/uranus/uranus_rings.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 90, resourceType: "diffuse", lifecycle: "resident", path: "planets/neptune/neptune_rings.png", lifetime: 6e4, colorSpace: "srgb" },
  { id: 91, resourceType: "specular", lifecycle: "streamable", path: "planets/earth/earth_specular.jpg", lifetime: 6e4, colorSpace: "srgb" }
]
